# Select GitHub markdown, all extensions are needed to get tables work correctly
markdown: kramdown

# Include all files used by Sphinx documentation
# Do not specify complete pattern e.g. doc/_static, it won't work.
include: ["_static", "_modules", "_images", "_sources", ".htaccess"]
